# -*- mode:python -*-

# Copyright (c) 2026 Zhantong Qiu, University of California, Davis
# and Cornell University
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

if env['CONF']['BUILD_ISA']:
    SimObject('Simple3CycleCPU.py', sim_objects=['Simple3CycleCPU'])

    Source('simple_3cycle_cpu.cc')
    Source('pipeline.cc')
    Source('pfu.cc')
    Source('decode.cc')
    Source('execute.cc')
    Source('lsq.cc')
    Source('stats.cc')

    DebugFlag('Simple3CPU',
              'Top-level Simple 3-cycle CPU events')
    DebugFlag('Simple3CPULineTrace',
              'One line per cycle, mirroring the Python prototype trace')
    DebugFlag('Simple3CPUFetch',
              'F stage: outgoing icache requests, streamId, fetchPc')
    DebugFlag('Simple3CPUResp',
              'IcachePort: incoming responses, streamId match/drop')
    DebugFlag('Simple3CPUPFU',
              'PFU FIFO: push, pop, filter on mispredict, deliverWord')
    DebugFlag('Simple3CPUDecode',
              'D stage: decoder transitions, static predict, flush bubble')
    DebugFlag('Simple3CPUExecute',
              'E stage: instr commit, mispredict detect, branch resolve')
    DebugFlag('Simple3CPUFlash',
              'Flash latency events: hit vs miss, bufferLine transitions')
    DebugFlag('Simple3CPULSQ',
              'LSQ: load/store push, complete, retry, release')

    CompoundFlag('Simple3CPUAll',
                 ['Simple3CPU', 'Simple3CPULineTrace', 'Simple3CPUFetch',
                  'Simple3CPUResp', 'Simple3CPUPFU', 'Simple3CPUDecode',
                  'Simple3CPUExecute', 'Simple3CPUFlash', 'Simple3CPULSQ'])
